name: e2e-kind

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.33.1

      # The setup-kind action is not maintained any more, and it also creates a
      # cluster which this test does not use. The test script creates its own.
      - name: Set up kind
        run: go install sigs.k8s.io/kind@v0.31.0

      - name: Run kind e2e test
        run: ./hack/e2e-test-with-kind.sh run
